version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "gatsby clean && gatsby develop -p 8000 -H '0.0.0.0'"
    ports:
      - "8000:8000"
    volumes:
      - /myapp/node_modules
      - .:/myapp
    environment:
      - NODE_ENV=development
