FROM node:12.14.0

RUN apt update && apt upgrade && \
    apt install gcc g++ make python git libc6-dev build-essential ligpng-dev libjpeg-dev

RUN npm install --global gatsby-cli node-gyp sharp --unsafe-perm

# The port gatsby runs on
EXPOSE 8000

WORKDIR /myapp
COPY ./package.json /myapp
COPY ./package-lock.json /myapp
RUN npm install --unsafe-perm
COPY . /myapp
CMD ["gatsby", "develop", "-H", "0.0.0.0" ]
